services:

  web:
    build: .
    command: >
      sh -c "
      make watch &
      poetry run ./manage.py migrate &&
      poetry run ./manage.py collectstatic --noinput &&
      DEBUG=1 exec poetry run ./manage.py runserver 0.0.0.0:8000
      "
    container_name: django_web
    environment:
      - SECRET_KEY=${SECRET_KEY-d}
      - PGHOST=${PGHOST-postgres}
      - PGUSER=${PGUSER-postgres}
      - PGPORT=${PGPORT-}
      - PGPASSWORD=${PGPASSWORD-postgres}
      - DB_NAME=${DB_NAME-postgres}
      - REDIS_URL=${REDIS_URL-redis://redis:6379}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - postgres
      - redis

  postgres:
    image: ghcr.io/baosystems/postgis:latest  # unofficial image that properly supports arm64 instead of 'postgis/postgis'
    tmpfs:
      - "/var/lib/postgresql/data/"
    # sloppy non-durable settings, which allegedly make the tests run faster
    # not to be used in production!
    command: --autovacuum=off --fsync=off --synchronous_commit=off --full_page_writes=off --work_mem=12MB --max-connections=10 --max_wal_senders=0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
