# Name of your application. Used to uniquely configure containers.
service: bustimes

# Name of the container image.
image: jclgoodwin/bustimes-org

# Deploy to these servers.
servers:
  - 10.131.29.248  # everglory
  - 10.131.0.24  # eveready
  - 10.131.33.248  # everest
  - 10.131.240.96  # everdainty

builder:
  multiarch: false

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: registry.digitalocean.com/hobsbawm
  # see https://github.com/settings/tokens
  username:
    - KAMAL_REGISTRY_PASSWORD
  password:
    - KAMAL_REGISTRY_PASSWORD

asset_path: /staticfiles

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    WEB_CONCURRENCY: 8
    ALLOWED_HOSTS: "*"
    EMAIL_HOST: email-smtp.eu-west-1.amazonaws.com
  secret:
    - TURNSTILE_SECRET
    - DATABASE_URL
    - REDIS_URL
    - SENTRY_DSN
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
    - TFL_APP_ID
    - TFL_APP_KEY
    - NTA_API_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /version
  port: 8000

# use `kamal traefik reboot --hosts=HOST` to deploy changes to this - best not to do all hosts at once
traefik:
  args:
    accesslog: true
    accesslog.fields.headers.names.user-agent: keep
    accesslog.fields.headers.names.referer: keep
    entrypoints.http.address: ":80" # for some reason, if trustedIPs is set then this must be set too
    entrypoints.http.forwardedHeaders.trustedIPs: 10.131.0.0/16
