name: Python application
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

    - uses: actions/checkout@v3

    - run: docker compose up -d

    - run: docker compose exec web poetry run ./manage.py collectstatic

    - name: Run tests
      run: docker compose exec web poetry run coverage run ./manage.py test -v3

    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
