name: bustimes.org

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - run: |
        npm install
        npm run lint
        npm test
        npm run build

    - name: Install Geospatial libraries
      # required by GeoDjango
      # see https://docs.djangoproject.com/en/dev/ref/contrib/gis/install/geolibs/
      run: |
        sudo apt-get update && sudo apt-get install binutils libproj-dev gdal-bin

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - run: poetry install

    - name: run tests
      env:
        SECRET_KEY: gdffesgfxc1as9rsxgv4
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        DB_NAME: postgres
      run: |
        poetry run ./manage.py collectstatic --noinput && \
        poetry run coverage run ./manage.py test && \
        poetry run coverage xml

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
