name: Python application
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: .docker
        key: docker-${{ hashFiles('Dockerfile') }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          docker-${{ hashFiles('Dockerfile') }}

    - run: docker compose up -d

    - name: Run tests
      run: |
        docker compose exec web poetry run coverage run ./manage.py test -v3
        docker compose exec web poetry run coverage json

    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
